@startuml
!include ./style.iuml
!pragma teoz true
hide footbox
skinparam CaptionBorderThickness 13
skinparam TitleFontSize 21
skinparam DefaultTextAlignment left
skinparam PackageTitleAlignment center

title Use Case 2: ATC Presciption 


participant "IDMP-enabled\nProduct Master" as CMPD

box Country A #F0FFFC
participant "Drug Database\nCountry A" as MPDA 
actor "Healthcare\nProfessional\nCountry A" as HCPA
participant "National Infrastructure\nCountry A (EHR)" as EHRA
participant "NCPeH\nCountry A" as NCA.A
end box


box Country B #FFF3F0
participant "NCPeH\nCountry B" as NCA.B
participant "National Infrastructure\nCountry B (EHR)" as EHRB
actor "Healthcare\nProfessional\nCountry B" as HCPB
participant "Drug Database\nCountry B" as MPDB
end box


group Distribute Product Master Data (country A)
CMPD -> MPDA
& CMPD -> MPDB: Provide Master data (ATC Codes)
end

...

group A1. Prescribe
HCPA -> EHRA : Prescription
activate EHRA
note right
**Attributes**
# Product Name 
# Substance 
## Substance Classification - ATC code
# Strength (Text)
# Dose form (Text)
# Dosage (Text)
endnote
end


group A2. Make document available for XBorder
EHRA -> NCA.A : Prescription
deactivate EHRA
activate NCA.A
'NCA.A -> NCA.A : Adapt/Transcode
deactivate NCA.A
end



...

group A5. Request and obtain prescription
HCPB --> EHRB: Request documents
& EHRB --> NCA.B: Request documents
& NCA.B --> NCA.A: Request documents
NCA.A --> NCA.B : Return prescription
& NCA.B --> EHRB : Return prescription
& EHRB --> HCPB : Return prescription
deactivate NCA.A
end

...

group 6. Select product for dispense
HCPB -> EHRB : Select products matching the input 
note right
**Attributes**
# Substance (Classification) - ATC code
# Strength (text?)
# Dose form (text?)
# Quantity (text?)
endnote
end


group 7. Register dispensed product
EHRB -> NCA.A : Submit dispensed product
note left
Attributes
# Substance (Classification) - ATC code
# Strength (text?)
# Dose form (text?)
# Quantity (text?)
endnote


end
...


'caption 
'This use case is related to the use of ATC in EPSOS
'The product classification replaces the use of an identifier
 
'The following attributes are expected:
'# Substance (Classification) - ATC code
'# Strength (text?)
'# Dose form (text?)
'# Quantity (text?)

'The use of a common code (ATC) allows the common understanding of the product. However, 
'that is not usually sufficient to characterize the prescribed product and definitely not the dispensed product

'endcaption
@enduml
