@startuml
!include ./style.iuml
!pragma teoz true
hide footbox
skinparam CaptionBorderThickness 13
skinparam TitleFontSize 21
skinparam DefaultTextAlignment left
skinparam PackageTitleAlignment center

title Use Case 3: Portuguese (Generic) CNPEM-based prescription\n Scenario 1 - Dispense in Italy

participant "IDMP-enabled\nProduct Master" as CMPD

box Country A #F0FFFC
participant "Drug Database\nCountry A" as MPDA 
actor "Healthcare\nProfessional\nCountry A" as HCPA
participant "National Infrastructure\nCountry A (EHR)" as EHRA
participant "NCPeH\nCountry A" as NCA.A
end box


box Country B #FFF3F0
participant "NCPeH\nCountry B" as NCA.B
participant "National Infrastructure\n/ EHR Country B" as EHRB
actor "Healthcare\nProfessional\nCountry B" as HCPB
participant "Drug Database\nCountry B" as MPDB
end box



group #EEF Distribute Product Master Data 
...
CMPD -> MPDA
& CMPD -> MPDB: Provide Master data  (Products and attributes - substance, strength, dose form, package sizes)
end

...

group A1. Prescribe
HCPA -> EHRA : Prescription
activate EHRA
note right
**Attributes**
# Product Identification
## Portugal
### CNPEM (generic) product code
### CNPEM (generic) product name
# dosage
## Total quantity
endnote
end


group A2. Make document available for XBorder
EHRA -> NCA.A : Prescription
note right
**Attributes**
# Product Identification
## Portugal
### CNPEM (generic) product code
### CNPEM (generic) product name
## EU
### {**substance, strength, dose form**}
### **package size**
# dosage
## **Total quantity**
endnote
deactivate EHRA
activate NCA.A
'NCA.A -> NCA.A : Adapt/Transcode
deactivate NCA.A


end



...

group A5. Request and obtain prescription
HCPB --> EHRB: Request documents
& EHRB --> NCA.B: Request documents
& NCA.B --> NCA.A: Request documents
NCA.A --> NCA.B : Return prescription
& NCA.B --> EHRB : Return prescription
& EHRB --> HCPB : Return prescription
deactivate NCA.A
end
...


group 6. Select product for dispense
HCPB -> EHRB : Select products matching the input 
note right
Matching Attributes
# Product Identification
## Italy
### Product Cluster Code
## EU
### {**substance, strength, dose form**}
### **package size**
# dosage
## **Total quantity**

endnote
end


group 7. Register dispensed product
EHRB -> NCA.A : Submit dispensed product
note left
Attributes
# Product Identification
## Italy
### Dispensed Product Code
## EU
### **MPID**
## **Lot number**
## **Expiry date**
# **Dosage**
## **Total quantity**
endnote

'caption 
'The following attributes are used:
'# Product Identification
'## PT
'### Product code (in PT referential)
'### Product name 
'## IT
'### Product code (in IT referential)
'### Product name 
'## EU
'### {**substance, strength, dose form**}
'### **package size**
'# **Dosage**
'## **Quantity**
'endcaption


@enduml
