@startuml
!include ./style.iuml
!pragma teoz true
hide footbox
skinparam DefaultTextAlignment left
skinparam PackageTitleAlignment center


'title Use Case: Branded prescription in country A - using attributes to identify products \nDispensing in country B - Identification of dispensed product in country A


participant "IDMP-enabled\nProduct Master" as CMPD

box Country A #F0FFFC
participant "Drug Database\nCountry A" as MPDA 
participant "NCA\nCountry A\n(NCPeH)" as NCA.A
participant "National Infrastructure\nCountry A (EHR)" as EHRA
actor "Healthcare\nProfessional\nCountry A" as HCPA
end box


box Country B #FFF3F0
participant "Drug Database\nCountry B" as MPDB
participant "NCA\nCountry B\n(NCPeH)" as NCA.B
participant "National Infrastructure\nCountry B (EHR)" as EHRB
actor "Healthcare\nProfessional\nCountry B" as HCPB
end box



group Distribute Product Master Data (country A)
CMPD -> MPDA: Provide Product Master data (IDMP levels)
& CMPD -> MPDB: Provide Product Master data (IDMP levels)
MPDA --> MPDA: Combine EU and national\nproduct identifiers and\nattributes on national level
MPDA --> EHRA: Distribute product identifiers and attributes
& MPDA --> HCPA
& MPDA -> NCA.A

MPDB -> MPDB: Combine EU and national\nproduct identifiers and\nattributes on national level
MPDB --> EHRB: Distribute product identifiers and attributes
& MPDB --> HCPB
& MPDB -> NCA.B
end



...

group A1. Prescribe
HCPA -> EHRA : Prescription
activate EHRA
note right
**Prescription data**
# Product Identification
## Country A
### **National Product identifier**
### **Product code**
### **Product name**
# **Dosage**
## In national terms (should be structured)
# **Amount to dispense**
## In national terms (should be structured)
...
endnote
end


group A2. Make document available for XBorder
EHRA -> NCA.A : Transcoded\nPrescription
deactivate EHRA
activate NCA.A
'NCA.A -> NCA.A : Adapt/Transcode
deactivate NCA.A
note right
**Prescription data**
# Product Identification
## Country A
### National Product identifier
### Product code
### Product name
## **EU**
### **Product identification**
#### **Best applicable IDMP identifiers**
### **Product specification**
#### **Key product attributes in IDMP vocabulary**
# **Dosage**
### In national terms
### **IDMP attributes when possible**
# **Amount to dispense**
### In national terms
### **Following IDMP guidelines**
endnote

end



...

group A5. Request and obtain prescription
HCPB -> EHRB: Request documents
'activate EHRB
& EHRB -> NCA.B: Request documents
'deactivate EHRB
'activate NCA.B
& NCA.B -> NCA.A: Request documents
'activate NCA.A
'deactivate NCA.B

NCA.A -> NCA.B : Return prescription

'activate HCPB
& NCA.B -> EHRB : Return prescription
& EHRB -> HCPB : Return prescription
deactivate NCA.A
'activate NCA.B
'deactivate NCA.B

end

...
group 6. Select product for dispense
HCPB -> EHRB : Select products matching the input 
note right
**Attributes for matching**
# Product Identification
## Country A
### National Product identifier
### Product code
### Product name
## **EU**
### **Product identification**
#### **Best applicable IDMP identifiers**
### **Product specification**
#### **Key product attributes in IDMP vocabulary**
# **Dosage**
### In national terms
### **IDMP attributes when possible**
# **Amount to dispense**
### In national terms
### **Following IDMP guidelines**
endnote


HCPB -> HCPB : Use the attributes to filter for matching products
note left
**Attributes**
# Product Identification
## EU
### {attributes that have a matching product in country B}
## Country B
### National Product identifiers
#### Product codes
#### Product names
endnote


HCPB -> HCPB : Select one product to dispense
note left
**Attributes**
# Product Identification
## Country B
### National Product identifier
### Product code
### Product name
## EU
### {attributes for selected product}
endnote

end


 
group 7. Register dispensed product
EHRB -> NCA.B : Submit dispensed product
note left
Attributes
# Product Identification
## Product B
### National product identifier
### Product code
### Product name
## **Lot number**
## **Expiry date**
# **Dosage**
## **Total quantity**
endnote
end



group 8. Register dispensed product in country A
NCA.B -> NCA.A : Submit dispense product
note left
Attributes
# **Product Identification**
## **Country B**
### National product identifier
### Product code
### Product name
## **EU Product identification**
### **Product identification**
#### **Best applicable IDMP identifiers**
### **Product specification**
#### **Key product attributes in IDMP vocabulary**
# **Dosage**
### In national terms
### **IDMP attributes when possible**
# **Amount to dispense**
### In national terms
### **Following IDMP guidelines**
## **Lot number**
## **Expiry date**
# **Dosage**
## **Total quantity**
## **Number of dispensed packages**
## **Package size**


endnote
end

@enduml
