@startuml
scale 600 width

state OriginalPrescription {
state "Active Principle" as long1
long1: Paracetamol
state "Strength" as long2
long2: 500 mg
state "Form" as long3
long3:  Tablets

}

state RelatedMedicationPrescription {
state "Active Principle" as long4
long4: Paracetamol
state "Strength" as long5
long5: 500 mg
state "Form" as long6
long6:  Tablets

}
long1 --> long4 : Direct
long2 --> long5 : Direct
long3 --> long6 : Direct

state OriginalDispense {
state "Active Principle" as a1
a1: Paracetamol
state "Strength" as s1
s1: 500 mg
state "Form" as f1
f1:  Tablets
state "Brand" as b1
b1:  Ben-u-ron

state "Size" as size1
size1:  20tabs



}

state RelatedMedicationDispense {
state "Active Principle" as a2
a2: Paracetamol
state "Strength" as s2
s2: 500 mg
state "Form" as f2
f2:  Tablets
state "Brand" as b2
b2:  Panadol

state "Size" as size2
size2:  20tabs
}

state RelatedMedicationDispense2 {
state "Active Principle" as a3
a3: Paracetamol
state "Strength" as s3
s3: 500 mg
state "Form" as f3
f3:  Tablets
state "Brand" as b3
b3:  Tylenol

state "Size" as size3
size3:  20tabs
}


a1 --> a2 : Multiple
s1 --> s2 : Multiple
f1 --> f2 : Multiple
b1 --> b2 : Multiple


a1 --> a3 : Multiple
s1 --> s3 : Multiple
f1 --> f3 : Multiple
b1 --> b3 : Multiple

@enduml


