@startuml
title Generic path
hide stereotype
hide circle
skinparam linetype polyline
skinparam shadowing false


'!pragma graphviz_dot smetana

skinparam class<<S>> {
BorderColor DarkSlateGray
BackgroundColor WhiteSmoke
HeaderBackgroundColor #909090
}

skinparam class<<PhP>> {
BorderColor #505090
BackgroundColor APPLICATION
HeaderBackgroundColor SkyBlue
}



skinparam class<<MP>> {
BorderColor DarkGreen
BackgroundColor PHYSICAL
HeaderBackgroundColor LimeGreen
}


skinparam class<<PMP>> {
BorderColor DarkRed
BackgroundColor MistyRose
HeaderBackgroundColor #f09090
}

skinparam class<<OD>> {
BorderColor SaddleBrown
BackgroundColor SandyBrown
HeaderBackgroundColor Coral
}


class "**OriginalPrescription**" as OP<<S>> {
    --
    |_ Active Principle: Paracetamol
      |_ System: PT     
    |_ Strength: 500 mg
      |_ System: PT    
    |_ Form: Tablets
      |_ System: PT
    --
    MedicationRequest (PhP)
}

class " **Pharmaceutical Product** " as RMP<<PhP>> {
    --
    |_ Active Principle: Paracetamol
      |_ System: EU     
    |_ Strength: 500 mg  
      |_ System: EU     
    |_ Form: Tablets
      |_ System: EU     
    |_ <color:gray>//Brand: --//
    |_ <color:gray>//Pack : -- //
    --
    relatedMedication
}

class " **OriginalDispense ** " as OD<<OD>>{
    --
    |_ Active Principle: Paracetamol
      |_ System: PT     
    |_ Strength: 500 mg
      |_ System: PT     
    |_ Form: Tablets
      |_ System: PT     
    |_ Brand: Ben-u-ron
      |_ System: PT     
    |_ Pack size: 20 tabs
      |_ System: PT     
    --
    MedicationDispense
}

class " **Medicinal Product**  " as ROD<<MP>>{
    --
    |_ Active Principle: Paracetamol
      |_ System: EU     
    |_ Strength: 500 mg
      |_ System: EU     
    |_ Form: Tablets
      |_ System: EU     
    |_ Brand: Ben-u-Ron
      |_ System: EU     
    |_ <color:gray>//Pack : -- //
    --
    relatedMedication
}

class " **Packaged Medicinal Product**  " as PMP<<PMP>>{
    --
    |_ Active Principle: Paracetamol
      |_ System: EU     
    |_ Strength: 500 mg    
      |_ System: EU     
    |_ Form: Tablets
      |_ System: EU     
    |_ Brand: Ben-U-Ron
      |_ System: EU     
    |_ PackSize: 20
      |_ System: EU     

    --
    relatedMedication
}




RMP <-l- OP: "Direct"

RMP <-r- OD: "Multiple"

ROD<-u- OD: "Multiple"

PMP <-d- OD: "Multiple"

@enduml