@startuml
title Wokflow 1 - generic path
skinparam actorStyle awesome

hide footbox

'!include ./style.iuml

actor "**Patient**" as P
actor "**GP**" as GP
actor "**Pharm**" as pharm

actor "**GP2**" as GP2

Participant "** GP **\n**  Software  **" as GPS
Participant "** Pharmacy **\n**  Software  **" as PPS

Participant "** Medication Vault  **" as V
Participant "** IDMP Reservoir  **" as idmp

group Medication Workflow
P --> GP: Appointment
GP -[#A92]-> GPS : Prescription
P --> pharm: into the pharmacy
pharm -[#A92]-> PPS : Dispense

end

GPS --> V: Data Storage
PPS --> V: Data Storage


group Data Transformation and Cross-data
GP2 -[#A92]-> V : Data Request
V --> idmp: Data Transformation
idmp --> V: Data return
V --> GP2: Information Return

end


@enduml
